version: '3.8'

services:
  admin-panel:
    build:
      context: ./flask_admin_panel
    ports:
      - "5001:5001"
    env_file: .env
    restart: unless-stopped

  bot-consultant:
    build:
      context: ./smartsec_bot
    env_file: .env
    restart: unless-stopped

  bot-tester:
    build:
      context: ./smartsec_testing
    ports:
      - "5000:5000"
    env_file: .env
    restart: unless-stopped